require('settings')
require('keys')

require('plugins.install')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.which-key')
require('plugins.toggleterm')
require('plugins.nvim-tree')
require('plugins.emmet')
require('plugins.autopairs')
